imports:
    - php

filter:
    excluded_paths:
        - vendor/*
        - tests/*

    dependency_paths:
        - vendor/

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    # version: 8.1.13
                    # version: 8.1.17
                    version: 8.2.4
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        before:
                # Reset and load game database
            -   command: "php bin/console app:reset-database"

                # Set up test database and load fixtures
            -   command: "php bin/console doctrine:fixtures:load --em=game --group=group1 --env=test --no-interaction"
        override:
            -   command: "composer phpunit --debug --verbose"
                # command: "XDEBUG_MODE=coverage  vendor/bin/phpunit" 
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
